services:
  locals3:
    image: minio/minio
    container_name: airflow-feat-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./minio/.env
    command: server --console-address ":9001" /data
    volumes:
      - locals3-data:/minio/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  locals3_init:
    build: ./minio/
    env_file:
      - ./minio/.env
    environment:
      - USER=user
      - COPY_DIR=false
      - INPUT_BUCKETS=api-data
    depends_on:
      - locals3
    entrypoint: /bin/sh ./entrypoint.sh

volumes:
  locals3-data:
