executor: "LocalKubernetesExecutor"

config:
  logging:
    remote_logging: 'True'
    remote_base_log_folder: 's3://airflow-logs'
    remote_log_conn_id: 'minio'
  webserver:
    expose_config: 'True'

secret:
  - envName: "AIRFLOW_CONN_MINIO"
    secretName: "minio"
    secretKey: "conn"


#postgresql:
#  enabled: true
#  postgresqlPassword: airflow
#  postgresqlUsername: airflow
#
#data:
##  metadataSecretName: databaseconn
#  # Otherwise pass connection values in
#  metadataConnection:
#    user: airflow
#    pass: airflow
#    protocol: postgresql
#    host: ~
#    port: 5432
#    db: airflow
#    sslmode: disable

webserver:
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: airflow
    password: airflow


triggerer:
  enabled: false

redis:
  enabled: false

statsd:
  enabled: false

cleanup:
  enabled: true


dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/mrn-aglic/examples.git # or replace with your github repo
    branch: main
    subPath: "airflow-new-features/dags/feat23/dags"
    sshKeySecret: airflow-git-secret
